### PR TITLE
User authentication

### PR DESCRIPTION
**Pull request by thepwagner**
Spec for reference: https://github.com/coreos/etcd/blob/master/Documentation/auth_api.md / https://github.com/coreos/etcd/blob/master/Documentation/authentication.md

### CODE REVIEW

**Comment by aheckmann** [comment]
+1

**Comment by dannysauer** [comment]
Hooray for authentication!

**Comment by lavagetto** [comment]
While I agree this is needed (and I was about to start working on it), I don't like the additional complexity that this PR creates.

- I would try not to make api_execute even more complex than it is now, also adding a conditional that is not needed
- User creation/administration are not matter for this library, I think. If you really want to have them outside of etcdctl I think they should be in a separate module (or at least in a separate file in this repo).

Sorry for the late feedback, but I was on vacation for the first time in two years and I completely disconnected.

@thepwagner do you want to work on this or should I do it?

**Comment by thepwagner** [comment]
Can do; it'll probably be a week or so before I can clean this up though.

The first commit may be worth a cherry-pick? (authentication support w/o user management cruft)

**Comment by lavagetto** [comment]
@thepwagner yes the first commit should be cherry-picked - I intended to do that myself :)

**Comment by lavagetto** [comment]
Just manually merged as it needed manual interventions. I'll work on making the code less duplicated as soon as possible.

Thanks again @thepwagner

**Pull request closed without merging**
