### PR TITLE
A couple of small fixes+improvements

### PR DESCRIPTION
**Pull request by smurfix**
See the patches. IMHO they're all pretty straightforward.

In particular, looking up the machine list suffered from a race condition, and looking up the leader only worked when you already happened to talk to the leader in the first place.

The SSL tests now pass, I removed the no-test markers (which don't work when testing with py.test).

I also sped up test startup by waiting until I'm able to connect (but at most three seconds), not two seconds per daemon. Tests now use just one server for the basic integration tests (which previously did not work because etcd complained about bad clustering or whatever), not a cluster-of-three.

### CODE REVIEW

**Comment by lavagetto** [comment]
Thanks for working on this @smurfix, it all seems very good, I'll get a closer look when I have one free moment.

**Comment by smurfix** [comment]
On 11.11.2015 12:47, Giuseppe Lavagetto wrote:
>
> Thanks for working on this @smurfix <https://github.com/smurfix>, it
> all seems very good, I'll get a closer look when I have one free moment.
>
Thanks.

Talking about enhancements, there are a couple of patches which add
username+password auth floating around on github …

-- 
-- Matthias Urlichs

**Comment by lavagetto** [comment]
@smurfix I will merge your patches a few at a time, I am a bit unsure about the machines lookup patch (I'm not saying it's wrong, I just need to think about it and I've just had a 60-hours workweek)

**Comment by smurfix** [comment]
On 15.11.2015 11:14, Giuseppe Lavagetto wrote:
>
> @smurfix <https://github.com/smurfix> I will merge your patches a few
> at a time, I am a bit unsure about the machines lookup patch (I'm not
> saying it's wrong, I just need to think about it and I've just had a
> 60-hours workweek)
>
I hear you WRT the work week. Mine isn't better.

-- 
-- Matthias Urlichs

**Comment by smurfix** [comment]
The current version hits a startup race condition in etcd when testing the auth features.
The latest patch adds a retry for that case.

**Comment by lavagetto** [comment]
closed as it's outdated now.

**Pull request closed without merging**
